export interface GlobalSettingPart {
  outdir_samples: string
  outdir_txt2img_samples: string
  outdir_img2img_samples: string
  outdir_extras_samples: string
  outdir_grids: string
  outdir_txt2img_grids: string
  outdir_img2img_grids: string
  outdir_save: string
  dataset_filename_word_regex: string
  dataset_filename_join_string: string
  sd_model_checkpoint: string
  sd_vae: string
  img2img_background_color: string
  deepbooru_filter_tags: string
  sd_hypernetwork: string
  font: string
  quicksettings: string
  ui_reorder: string
  ui_extra_networks_tab_reorder: string
  localization: string
  show_progress_type: string
  live_preview_content: string
  ddim_discretize: string
  sd_checkpoint_hash: string
  sd_lora: string
  control_net_model_config: string
  control_net_model_adapter_config: string
  control_net_models_path: string
  additional_networks_extra_lora_path: string
}
